# Generated by Django 5.2.7 on 2025-10-17 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('formateur', models.CharField(max_length=100, verbose_name='Formateur')),
                ('capacite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité maximale')),
                ('statut', models.CharField(choices=[('PROGRAMMEE', 'Programmée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PROGRAMMEE', max_length=15, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('role', models.CharField(choices=[('RH', 'Responsable RH'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=10, verbose_name='Rôle')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('poste', models.CharField(max_length=100, verbose_name='Poste')),
                ('departement', models.CharField(max_length=100, verbose_name='Département')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('CONGE', 'En congé')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employes/', verbose_name='Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI - Contrat à durée indéterminée'), ('CDD', 'CDD - Contrat à durée déterminée'), ('STAGE', 'Stage'), ('INTERIM', 'Intérim'), ('APPRENTISSAGE', 'Apprentissage')], max_length=15, verbose_name='Type de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('poste', models.CharField(max_length=100, verbose_name='Poste')),
                ('departement', models.CharField(max_length=100, verbose_name='Département')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('document', models.FileField(blank=True, null=True, upload_to='contrats/', verbose_name='Document')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='rh_app.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé annuel'), ('MALADIE', 'Congé maladie'), ('MATERNITE', 'Congé maternité'), ('PATERNITE', 'Congé paternité'), ('SANS_SOLDE', 'Congé sans solde'), ('SPECIAL', 'Congé spécial')], max_length=15, verbose_name='Type de congé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('nombre_jours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de jours')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('commentaire_rh', models.TextField(blank=True, verbose_name='Commentaire RH')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='rh_app.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_formation', to='rh_app.employe', verbose_name='Employé')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='rh_app.formation', verbose_name='Formation')),
            ],
            options={
                'verbose_name': 'Inscription formation',
                'verbose_name_plural': 'Inscriptions formations',
                'ordering': ['-date_inscription'],
                'unique_together': {('employe', 'formation')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'Retard'), ('CONGE', 'En congé'), ('TELETRAVAIL', 'Télétravail')], default='PRESENT', max_length=15, verbose_name='Statut')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='rh_app.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date'],
                'unique_together': {('employe', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire de base')),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Primes')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Déductions')),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net')),
                ('date_paiement', models.DateField(verbose_name='Date de paiement')),
                ('bulletin', models.FileField(blank=True, null=True, upload_to='bulletins/', verbose_name='Bulletin de paie')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='rh_app.employe', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Salaire',
                'verbose_name_plural': 'Salaires',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
